import json
import string
import re
import os
import sys

# ==========================================
# STRING NORMALIZATION & QAMPARI METRICS (官方逻辑)
# ==========================================

def normalize_answer(s):
    def remove_articles(text):
        return re.sub(r'\b(a|an|the)\b', ' ', text)
    def white_space_fix(text):
        return ' '.join(text.split())
    def remove_punc(text):
        exclude = set(string.punctuation)
        return ''.join(ch for ch in text if ch not in exclude)
    def lower(text):
        return text.lower()
    
    if s is None:
        return ""
    return white_space_fix(remove_articles(remove_punc(lower(str(s)))))

def qampari_list_recall(prediction, ground_truth_lists):
    """
    Calculates the percentage of distinct ground truth entities successfully 
    generated by the model. 
    """
    if not ground_truth_lists:
        return 0.0

    # Sanitize format: 兼容咱们之前在生成脚本里展平的 ground_truth 列表
    if isinstance(ground_truth_lists, str):
        ground_truth_lists = [[ground_truth_lists]]
    elif isinstance(ground_truth_lists, list) and len(ground_truth_lists) > 0 and isinstance(ground_truth_lists[0], str):
        ground_truth_lists = [[gt] for gt in ground_truth_lists]

    norm_pred = normalize_answer(prediction)
    found_count = 0
    
    for entity_aliases in ground_truth_lists:
        # If the model generated ANY valid alias for this specific entity, count it.
        if any(normalize_answer(alias) in norm_pred for alias in entity_aliases):
            found_count += 1
            
    # Recall = (Entities Found) / (Total Entities Required)
    return (found_count / len(ground_truth_lists)) * 100

# ==========================================
# EVALUATION LOOP (适配 Saber Checkpoint 格式)
# ==========================================

def evaluate_qampari_file(filepath):
    if not os.path.exists(filepath) or os.path.getsize(filepath) == 0:
        print(f"Error: File {filepath} not found or is empty.")
        return

    # 用于按方法(Method)分别统计召回率
    metrics_per_method = {}

    with open(filepath, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            
            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                print(f"Warning: JSON decode error on line {line_num}")
                continue
                
            # 提取 Ground Truth
            ground_truths = data.get("ground_truth", [])
            if not ground_truths:
                continue

            results = data.get("results", {})
            for method, method_data in results.items():
                if not method_data.get("success"):
                    continue
                    
                prediction = method_data.get("generated_text", "")
                
                if method not in metrics_per_method:
                    metrics_per_method[method] = {"recall": 0.0, "count": 0}

                # 计算 QAMPARI 专属的 List Recall
                recall = qampari_list_recall(prediction, ground_truths)

                metrics_per_method[method]["recall"] += float(recall)
                metrics_per_method[method]["count"] += 1

    if not metrics_per_method:
        print(f"[{filepath}]\nNo valid prediction/answer pairs found.\n")
        return

    # 打印 QAMPARI 成绩单表格
    print("\n" + "=" * 65)
    print(f"📊 QAMPARI EXHAUSTIVE LIST RECALL REPORT")
    print(f"📁 Source: {os.path.basename(filepath)}")
    print("=" * 65)
    print(f"{'Method':<20} | {'Samples':<7} | {'Avg List Recall (%)':>20}")
    print("-" * 65)
    
    for method, scores in metrics_per_method.items():
        count = scores["count"]
        avg_recall = scores["recall"] / count
        print(f"{method:<20} | {count:<7} | {avg_recall:>19.2f}%")
    print("=" * 65 + "\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python official_judge_qampari.py <file1.jsonl> <file2.jsonl> ...")
        sys.exit(1)
        
    for file_path in sys.argv[1:]:
        evaluate_qampari_file(file_path)